# Generated by Django 3.2.13 on 2022-05-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Адресс')),
                ('index', models.PositiveIntegerField(blank=True, default='индекс не указан', null=True, verbose_name='индекс')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронный адрес')),
            ],
            options={
                'verbose_name': 'Продукт',
                'ordering': ('city', 'pk'),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
    ]
