# Generated by Django 3.2.13 on 2022-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220526_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ('city', 'pk'), 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Действующий'),
        ),
    ]
